name: quikguardtrue
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.8

  # Firebase
  permission_handler: ^12.0.1

  permission_handler_android: ^13.0.1
  permission_handler_apple: ^9.4.7
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4   # ✅ ใช้กับ Flutter 3.8 ได้แน่นอน
  get_storage: ^2.1.1

  # อื่น ๆ
  google_fonts: ^6.2.1
  image_picker: ^1.1.2        # ✅ รองรับ Flutter 3.8
  uuid: ^4.5.1

  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/safety.jpg
