// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_6pGL1jYPB14CtJbzHtAlOZEiNzeBMbE',
    appId: '1:118780314746:web:8b53efb9403edb7d54a7c3',
    messagingSenderId: '118780314746',
    projectId: 'quickguard-3d3bb',
    authDomain: 'quickguard-3d3bb.firebaseapp.com',
    storageBucket: 'quickguard-3d3bb.firebasestorage.app',
    measurementId: 'G-BNGGXBKESM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrtprW6fB8eegJtpi7WICIfYTtQIkUddM',
    appId: '1:118780314746:android:64a27a7060e4451854a7c3',
    messagingSenderId: '118780314746',
    projectId: 'quickguard-3d3bb',
    storageBucket: 'quickguard-3d3bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByQTM7dhTy41MKnTM4i33HBaiVYBy01PQ',
    appId: '1:118780314746:ios:5a781928018728c954a7c3',
    messagingSenderId: '118780314746',
    projectId: 'quickguard-3d3bb',
    storageBucket: 'quickguard-3d3bb.firebasestorage.app',
    iosBundleId: 'com.example.quikguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByQTM7dhTy41MKnTM4i33HBaiVYBy01PQ',
    appId: '1:118780314746:ios:5a781928018728c954a7c3',
    messagingSenderId: '118780314746',
    projectId: 'quickguard-3d3bb',
    storageBucket: 'quickguard-3d3bb.firebasestorage.app',
    iosBundleId: 'com.example.quikguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_6pGL1jYPB14CtJbzHtAlOZEiNzeBMbE',
    appId: '1:118780314746:web:2c6f902e7811e17954a7c3',
    messagingSenderId: '118780314746',
    projectId: 'quickguard-3d3bb',
    authDomain: 'quickguard-3d3bb.firebaseapp.com',
    storageBucket: 'quickguard-3d3bb.firebasestorage.app',
    measurementId: 'G-3HLLQ6NG5Y',
  );
}
